import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
MODELS_DIR = os.path.join(BASE_DIR, "..", "models")
PROCESSED_DIR = os.path.join(BASE_DIR, "..", "processed")

MODEL_PATH = os.path.join(MODELS_DIR, "best_model.pkl")
MODEL_COMPARISON_PATH = os.path.join(MODELS_DIR, "model_comparison.csv")
FEATURE_IMPORTANCE_PATH = os.path.join(MODELS_DIR, "feature_importance.csv")
RISK_SEGMENTS_PATH = os.path.join(MODELS_DIR, "risk_segments.csv")
PORTFOLIO_SCORES_PATH = os.path.join(MODELS_DIR, "customer_risk_scores.csv")
FEATURE_TABLE_PATH = os.path.join(PROCESSED_DIR, "final_feature_table.csv")

FEATURE_LABELS = {
    "EXT_SOURCE_MEAN": "Average External Credit Score",
    "EXT_SOURCE_1": "External Credit Score 1",
    "EXT_SOURCE_2": "External Credit Score 2",
    "EXT_SOURCE_3": "External Credit Score 3",
    "EXT_SOURCE_MIN": "Minimum External Credit Score",
    "EXT_SOURCE_MAX": "Maximum External Credit Score",
    "EXT_SOURCE_PRODUCT": "External Score Product",
    "EXT_SOURCE_STD": "External Score Variability",
    "inst_pct_late": "Late Payment Percentage",
    "inst_num_early": "Number of Early Payments",
    "inst_num_late": "Number of Late Payments",
    "inst_num_ontime": "Number of On-Time Payments",
    "inst_max_delay": "Maximum Payment Delay (days)",
    "inst_avg_delay": "Average Payment Delay (days)",
    "inst_median_delay": "Median Payment Delay (days)",
    "inst_pct_early": "Early Payment Percentage",
    "inst_pct_ontime": "On-Time Payment Percentage",
    "AMT_ANNUITY": "Loan Annuity Amount",
    "AMT_CREDIT": "Credit Amount",
    "AMT_INCOME_TOTAL": "Annual Income",
    "AMT_GOODS_PRICE": "Goods Price",
    "CREDIT_GOODS_RATIO": "Credit-to-Goods Ratio",
    "CREDIT_INCOME_RATIO": "Credit-to-Income Ratio",
    "ANNUITY_INCOME_RATIO": "Annuity-to-Income Ratio",
    "INCOME_PER_PERSON": "Income Per Family Member",
    "DAYS_BIRTH": "Customer Age (days)",
    "AGE_YEARS": "Customer Age (years)",
    "DAYS_EMPLOYED": "Employment Duration (days)",
    "EMPLOYED_YEARS": "Employment Duration (years)",
    "DAYS_ID_PUBLISH": "ID Document Age (days)",
    "DAYS_REGISTRATION": "Registration Age (days)",
    "DAYS_LAST_PHONE_CHANGE": "Last Phone Change (days)",
    "CNT_CHILDREN": "Number of Children",
    "CNT_FAM_MEMBERS": "Family Size",
    "OWN_CAR_AGE": "Car Age (years)",
    "bureau_max_days_credit": "Max Bureau Credit Duration",
    "bureau_mean_debt": "Average Bureau Debt",
    "bureau_active_credit_count": "Active Bureau Credits",
    "bureau_max_credit_sum": "Maximum Bureau Credit Sum",
    "bureau_mean_credit_sum": "Average Bureau Credit Sum",
    "bureau_total_credit_sum": "Total Bureau Credit Sum",
    "bureau_total_debt": "Total Bureau Debt",
    "bureau_max_debt": "Maximum Bureau Debt",
    "bureau_closed_credit_count": "Closed Bureau Credits",
    "bureau_count": "Total Bureau Inquiries",
    "bureau_max_overdue": "Maximum Bureau Overdue Amount",
    "bureau_mean_overdue": "Average Bureau Overdue",
    "bureau_total_overdue": "Total Bureau Overdue",
    "bureau_bad_debt_count": "Bureau Bad Debt Count",
    "bureau_mean_days_credit": "Average Bureau Credit Duration",
    "bureau_sold_credit_count": "Sold Bureau Credits",
    "prev_avg_prev_annuity": "Avg Previous Loan Annuity",
    "prev_max_prev_credit": "Max Previous Loan Credit",
    "prev_avg_down_payment": "Avg Previous Down Payment",
    "prev_refusal_rate": "Previous Loan Refusal Rate",
    "prev_approval_rate": "Previous Loan Approval Rate",
    "prev_avg_prev_credit": "Avg Previous Loan Credit",
    "prev_num_approved": "Number of Approved Loans",
    "prev_num_prev_apps": "Total Previous Applications",
    "prev_num_canceled": "Number of Cancelled Loans",
    "prev_num_refused": "Number of Refused Loans",
    "cc_max_utilization": "Max Credit Card Utilization",
    "cc_avg_utilization": "Avg Credit Card Utilization",
    "cc_avg_credit_limit": "Avg Credit Card Limit",
    "cc_avg_drawings": "Avg Credit Card Drawings",
    "cc_avg_balance": "Avg Credit Card Balance",
    "cc_max_balance": "Max Credit Card Balance",
    "cc_avg_payment": "Avg Credit Card Payment",
    "CODE_GENDER_M": "Gender: Male",
    "CODE_GENDER_F": "Gender: Female",
    "FLAG_OWN_CAR_Y": "Owns a Car",
    "FLAG_OWN_CAR_N": "No Car",
    "FLAG_WORK_PHONE": "Has Work Phone",
    "FLAG_PHONE": "Has Phone",
    "FLAG_EMAIL": "Has Email",
    "FLAG_EMP_PHONE": "Has Employer Phone",
    "NAME_EDUCATION_TYPE_Higher education": "Higher Education",
    "NAME_EDUCATION_TYPE_Secondary / secondary special": "Secondary Education",
    "NAME_EDUCATION_TYPE_Incomplete higher": "Incomplete Higher Education",
    "NAME_EDUCATION_TYPE_Lower secondary": "Lower Secondary Education",
    "NAME_EDUCATION_TYPE_Academic degree": "Academic Degree",
    "NAME_CONTRACT_TYPE_Cash loans": "Cash Loan",
    "NAME_CONTRACT_TYPE_Revolving loans": "Revolving Loan",
    "REGION_POPULATION_RELATIVE": "Region Population Density",
    "REGION_RATING_CLIENT": "Region Rating",
    "REGION_RATING_CLIENT_W_CITY": "Region Rating (with City)",
    "REG_CITY_NOT_LIVE_CITY": "Registration ≠ Living City",
    "HOUSETYPE_MODE_block of flats": "Lives in Block of Flats",
    "EXT_SOURCE_COUNT_AVAILABLE": "External Scores Available",
    "DAYS_EMPLOYED_ANOM": "Employment Data Anomaly",
    "FLAG_DOCUMENT_3": "Document 3 Provided",
    "DEF_60_CNT_SOCIAL_CIRCLE": "Social Circle Defaults (60 days)",
    "DEF_30_CNT_SOCIAL_CIRCLE": "Social Circle Defaults (30 days)",
    "OBS_60_CNT_SOCIAL_CIRCLE": "Social Circle Observations (60 days)",
    "OBS_30_CNT_SOCIAL_CIRCLE": "Social Circle Observations (30 days)",
    "AMT_REQ_CREDIT_BUREAU_QRT": "Bureau Inquiries (Quarter)",
    "AMT_REQ_CREDIT_BUREAU_YEAR": "Bureau Inquiries (Year)",
    "AMT_REQ_CREDIT_BUREAU_MON": "Bureau Inquiries (Month)",
    "AMT_REQ_CREDIT_BUREAU_WEEK": "Bureau Inquiries (Week)",
    "AMT_REQ_CREDIT_BUREAU_DAY": "Bureau Inquiries (Day)",
    "AMT_REQ_CREDIT_BUREAU_HOUR": "Bureau Inquiries (Hour)",
    "HOUR_APPR_PROCESS_START": "Application Hour",
}
